### PR TITLE
MTL-1910 `pre-install-toolkit` is an NCN image

### PR DESCRIPTION
**Pull request by rustydb**
### Summary and Scope

- Fixes: MTL-1910

#### Issue Type

- RFE Pull Request

This change makes the pre-install-toolkit inherit from the `non-compute-common` layer, removing the need to update two places for packages. By not having to update two place we can avoid accidents, such as updating the kernel for the NCN and forgetting to update the PIT. Other packages like `craycli` also fail to be updated in all the necessary places, sometimes.

- New packages to the PIT: `ceph-common`, `cfs*`, `cos`,
  `dracut-metal-mdsquash`, and `goss-servers` (not harmful)
- New packages to storage-ceph: `loftsman` and `manifestgen` now live in
  node-images-common
- Removed duplicates: `kernel-*`, `python*`, `craycli`, `hpe-csm-*`, (virtually)
  every OS package (e.g. `vim`, libraries, and more), `biosdevname`, `grub2*`,
  `mft`

### Prerequisites

- [ ] I have included documentation in my PR (or it is not required)
- [ ] I tested this on internal system (if yes, please include results or a description of the test)
- [ ] I tested this on a vshasta system (if yes, please include results or a description of the test)

### Risks and Mitigations
 

This adds more packages to the LiveCD that won't necessarily be used.

### CODE REVIEW

**Comment by jpdavis-prof** [comment]
Can we move any of these into the common layer or consolidate in some way?

```
extra.packages:cfs-trust=1.6.0-1
node-image-non-compute-common/base.packages:cfs-trust=1.6.0-1
----
cray-pre-install-toolkit/base.packages:conman=0.3.0-1.42
node-image-non-compute-common/base.packages:conman=0.3.0-1.42
----
cray-pre-install-toolkit/base.packages:craycli=0.61.0-1
node-image-non-compute-common/base.packages:craycli=0.61.0-1
----
cray-pre-install-toolkit/base.packages:dnsmasq=2.86-150100.7.20.1
node-image-non-compute-common/base.packages:dnsmasq=2.86-150100.7.20.1
----
cray-pre-install-toolkit/base.packages:jq=1.6-3.3.1
node-image-storage-ceph/base.packages:jq=1.6-3.3.1
----
node-image-kubernetes/metal.packages:keepalived=2.0.19-bp152.1.9
node-image-storage-ceph/metal.packages:keepalived=2.0.19-bp152.1.9
----
cray-pre-install-toolkit/base.packages:loftsman=1.2.0-1
node-image-kubernetes/base.packages:loftsman=1.2.0-1
----
cray-pre-install-toolkit/base.packages:manifestgen=1.3.7-1
node-image-kubernetes/base.packages:manifestgen=1.3.7-1
----
cray-pre-install-toolkit/base.packages:netcat-openbsd=1.178-1.24
node-image-storage-ceph/base.packages:netcat-openbsd=1.178-1.24
```

**Comment by rustydb** [comment]
> Can we move any of these into the common layer or consolidate in some way?
> 
> ```
> extra.packages:cfs-trust=1.6.0-1
> node-image-non-compute-common/base.packages:cfs-trust=1.6.0-1
> ----
> cray-pre-install-toolkit/base.packages:conman=0.3.0-1.42
> node-image-non-compute-common/base.packages:conman=0.3.0-1.42
> ----
> cray-pre-install-toolkit/base.packages:craycli=0.61.0-1
> node-image-non-compute-common/base.packages:craycli=0.61.0-1
> ----
> cray-pre-install-toolkit/base.packages:dnsmasq=2.86-150100.7.20.1
> node-image-non-compute-common/base.packages:dnsmasq=2.86-150100.7.20.1
> ----
> cray-pre-install-toolkit/base.packages:jq=1.6-3.3.1
> node-image-storage-ceph/base.packages:jq=1.6-3.3.1
> ----
> node-image-kubernetes/metal.packages:keepalived=2.0.19-bp152.1.9
> node-image-storage-ceph/metal.packages:keepalived=2.0.19-bp152.1.9
> ----
> cray-pre-install-toolkit/base.packages:loftsman=1.2.0-1
> node-image-kubernetes/base.packages:loftsman=1.2.0-1
> ----
> cray-pre-install-toolkit/base.packages:manifestgen=1.3.7-1
> node-image-kubernetes/base.packages:manifestgen=1.3.7-1
> ----
> cray-pre-install-toolkit/base.packages:netcat-openbsd=1.178-1.24
> node-image-storage-ceph/base.packages:netcat-openbsd=1.178-1.24
> ```

Some of those are already moved into the common layer.

The only ones that aren't are:
- dnsmasq (we don't want this on the NCN, it's a PIT tool)
- keepalived could be consolidated
- netcat-openbsd could be consolidated

The rest of those already are in common but I'll double-check.

**Comment by jpdavis-prof** [comment]
Looks like README.adoc and scripts/update-package-versions.sh still reference *node-image-non-compute-common* vs. *node-image-common* in several places.

**Comment by jpdavis-prof** [comment]
> 
> Some of those are already moved into the common layer.
> 
> The only ones that aren't are:
> 
> * dnsmasq (we don't want this on the NCN, it's a PIT tool)
> * keepalived could be consolidated
> * netcat-openbsd could be consolidated
> 
> The rest of those already are in common but I'll double-check.

This is a better list. Some are duplicated in common and downstream layers. Some could be moved to common it looks like.
```
extra.packages:cfs-trust=1.6.0-1
node-image-common/base.packages:cfs-trust=1.6.0-1
----
node-image-common/base.packages:conman=0.3.0-1.42
node-image-pre-install-toolkit/base.packages:conman=0.3.0-1.42
----
node-image-kubernetes/metal.packages:haproxy=2.0.14-bp152.1.1
node-image-storage-ceph/metal.packages:haproxy=2.0.14-bp152.1.1
----
node-image-common/base.packages:jq=1.6-3.3.1
node-image-storage-ceph/base.packages:jq=1.6-3.3.1
----
node-image-kubernetes/metal.packages:keepalived=2.0.19-bp152.1.9
node-image-storage-ceph/metal.packages:keepalived=2.0.19-bp152.1.9
----
node-image-common/base.packages:loftsman=1.2.0-1
node-image-kubernetes/base.packages:loftsman=1.2.0-1
----
node-image-common/base.packages:manifestgen=1.3.7-1
node-image-kubernetes/base.packages:manifestgen=1.3.7-1
----
node-image-pre-install-toolkit/base.packages:netcat-openbsd=1.178-1.24
node-image-storage-ceph/base.packages:netcat-openbsd=1.178-1.24
```

**Comment by rustydb** [comment]
@jpdavis-prof think I handled them all now.

**Review by jpdavis-prof — APPROVED** [review]

**Pull request merged**
